### ISSUE TITLE
must be an instance of Predis\\Client, instance of Redis given

### ISSUE THREAD

**Issue by sanchobouillant** [jaytaph/RateLimitBundle#110]
Hi,

I Installed SncRedis and RateLimit with Symfony 5. When I try a route I have the error:

> Argument 1 passed to Noxlogic\\RateLimitBundle\\Service\\Storage\\Redis::__construct() must be an instance of Predis\\Client, instance of Redis given, called in /var/application/var/cache/dev/ContainerEdVmABd/App_KernelDevDebugContainer.php on line 8263

snc_redis.yaml

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"`

```
noxlogic_rate_limit.yaml:

```
noxlogic_rate_limit:
    enabled: true
    redis_client: default
    storage_engine: redis
    php_redis_service: default
```

Should I configure something else?
