### ISSUE TITLE
How to overwrite limit specific group or domain or client?

### ISSUE THREAD

**Issue by kgpanteon** [jaytaph/RateLimitBundle#126]
The global path limit applying limit to all users. Is there anyway to overwrite limit for specific users?

**Comment by kgpanteon** [comment]
@jaytaph Able to  achieve it

**services.yml**

```
apibundle.listener.rate_limit_checked.set:
        class: ApiBundle\EventListener\ClientRateLimitListener  
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: 'ratelimit.checked.ratelimit', method: 'setRateLimit' }
```

ClientRateLimitListener.php
```     
<?php

namespace ApiBundle\EventListener;

use Noxlogic\RateLimitBundle\Events\CheckedRateLimitEvent;
use Symfony\Component\HttpFoundation\RequestStack;
use Noxlogic\RateLimitBundle\Annotation\RateLimit;


class ClientRateLimitListener  {

    /**
     * @var RequestStack
     */
    private $requestStack;
    private $container = null;

    /**
     * @param RequestStack $requestStack
     */
    public function __construct(RequestStack $requestStack) {
        $this->requestStack = $requestStack;
    }

    public function setRateLimit(CheckedRateLimitEvent $checkedRateLimitEvent) {

        $request = $this->requestStack->getCurrentRequest();
        $customHeader = $request->headers->get('x-custom-header');

        if (!empty($customHeader ) && !is_null($customHeader )) {
            $checkedRateLimitEvent->setRateLimit(new RateLimit(array(
                'limit' => 1000,
                'period' => 60,
                'methods' => array(0 => '*')
            )));
        }
    }

}
```
