### ISSUE TITLE
RateLimitBundle\Service\Storage\Redis expects Predis\Client injection

### ISSUE THREAD

**Issue by guatebus** [jaytaph/RateLimitBundle#15]
`\Noxlogic\RateLimitBundle\Service\Storage\Redis::__construct()` type-hints the constructor parameter to `Predis\Client`.

When using phpredis on the snc/SncRedisBundle (see the config below) the following exception is thrown:

`ErrorException: Catchable Fatal Error: Argument 1 passed to Noxlogic\RateLimitBundle\Service\Storage\Redis::__construct() must be an instance of Predis\Client, instance of Snc\RedisBundle\Client\Phpredis\Client given, called in ...app/cache/dev/appDevDebugProjectContainer.php on line 5157 and defined in ...vendor/noxlogic/ratelimit-bundle/Noxlogic/RateLimitBundle/Service/Storage/Redis.php line 15`

FYI the RateLimitBundle works if the type-hint on the constructor is removed, but a proper fix is needed. Will see if I have time to dig into it and come up with a clean solution as a PR.

snc/SncRedisBundle config:

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
```

**Comment by mcfedr** [comment]
Fixed in 1.8, set `php_redis_service: snc_redis.default`

**Comment by tom10271** [comment]
It is still not working in 1.14

```
Exception: Argument 1 passed to Noxlogic\RateLimitBundle\Service\Storage\Redis::__construct() must be an instance of Predis\Client, instance of Redis given, called in /Users/user/myProject/app/cache/dev/appDevDebugProjectContainer.php on line 7969
```

```yml
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%redis.host%'
            logging: false

noxlogic_rate_limit:
    enabled:               true
    storage_engine:        redis
    php_redis_service:     snc_redis.default
    rate_response_code:    429
    rate_response_message: Rate limit reached
    display_headers:       false
    path_limits:
        -
            path:          /login
            limit:         12
            period:        3600
```
