### ISSUE TITLE
Configurable default rate-limit

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/RateLimitBundle#5]
Add default x-rate limit to config (like: rate-limiting an /api directory for instance)

For instance:

```
ratelimitbundle:
   default:
     path: /api
     method: GET
     limit: 100
     period: 60
```
