### ISSUE TITLE
Limit not working on login url

### ISSUE THREAD

**Issue by pohlaniacz** [jaytaph/RateLimitBundle#56]
Hi, I've tried to prevent brute forcing by add limit to post login action but it looks like it ommit it? I've passed limit to other action and it looks ok..

security.yml
```yml
security:
    firewalls:
        main:
            pattern:    ^/
            provider: user
            security: true
            anonymous:  true
            switch_user: true
            form_login:
                check_path: login
                login_path: login
                failure_path:    /
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                success_handler: user_security.success_handler
                failure_handler: user_security.failure_handler
```

controller
```php
/**
 * @RateLimit(limit=2, period=60)
 *
 * @Route("/login", name="login")
 * @param Request $request
 * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
 */
public function loginAction(Request $request)
{
	$authenticationUtils = $this->get('security.authentication_utils');

	// get the login error if there is one
	$error = $authenticationUtils->getLastAuthenticationError();

	// last username entered by the user
	$lastUsername = $authenticationUtils->getLastUsername();

	return $this->render(
		'Acme:Demo:login.html.twig',
		[
			'last_username' => $lastUsername,
			'login_error' => $error,
		]
	);
}
```
