### ISSUE TITLE
The service "noxlogic_rate_limit.storage" has a dependency on a non-existent service "snc_redis.default_client".

### ISSUE THREAD

**Issue by pohlaniacz** [jaytaph/RateLimitBundle#77]
Hi, after updating from 1.7.0 to newer versions I've get an error when clearCache is called:

The service "noxlogic_rate_limit.storage" has a dependency on a non-existent service "snc_redis.default_client".

Bug starts from updating to 1.81. I don't need to snc bundle because im using doctrine_cache. My config looks ok and it's working fine now:

```
doctrine_cache:
    providers:
        memcached_cache:
            memcached:
                connection_id: memcached
        redis_cache:
            redis:
                connection_id: redis

noxlogic_rate_limit:
    enabled: true
    storage_engine: "doctrine"
    doctrine_provider: redis_cache
    rate_response_exception: Api\AppBundle\Exception\RateExceededException
    rate_response_code: 429
    rate_response_message: 'You exceeded the rate limit'
    display_headers: true
    headers:
        limit: X-RateLimit-Limit
        remaining: X-RateLimit-Remaining
        reset: X-RateLimit-Reset
```

**Comment by mcfedr** [comment]
This is strange, should be working just fine, I just added a test to check this, and it worked. https://github.com/jaytaph/RateLimitBundle/pull/78

Maybe you can put the debugger in NoxlogicRateLimitExtension::loadServices and see what happens, it should update the definition of `noxlogic_rate_limit.storage` with reference to your doctrine provider service

**Comment by dimitrelsen** [comment]
I'm trying to install the package in symfony 4.2 and i'm getting the same error: The service "noxlogic_rate_limit.rate_limit_annotation_listener" has a dependency on a non-existent service "snc_redis.default_client". Actually i have a symfony 4.0 project and it works well, but not in symfony 4.2

**Comment by Pixadelic** [comment]
It happens to me the same issue installing the package in symfony 4.2. I'm looking how to resolve it. In the meantime, if anybody has started to analyse this issue thanks for sharing.

**Comment by danbadds38** [comment]
> It happens to me the same issue installing the package in symfony 4.2. I'm looking how to resolve it. In the meantime, if anybody has started to analyse this issue thanks for sharing.

let me know!

**Comment by joaojacome** [comment]
Open the file config/packages/snc_redis.yaml and uncomment the following lines
`        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
`

**Comment by alister** [comment]
If using Redis is only an option for use of this bundle, why is it being required as a dependency?

**Comment by alister** [comment]
I've got snc/redisbundle v3 installed, and they have removed the '*_client' services.

There are two ways to fix this:
1/ Alias it back as a public service:

    services:
        snc_redis.default_client: '@snc_redis.default'

2/ Better, change the noxlogic_rate_limit configuration: config/packages/noxlogic_rate_limit.yaml
```
noxlogic_rate_limit:
    storage_engine: redis
    enabled: true
    # this is pre-configured to be `default_client` (referring to snc_redis.default_client)
    # use the 'modern' service name.
    redis_client: default 
```

For @pohlaniacz - since the 'redis_client' has a default being set internally, you will need to explicitly configure it as `null` in the configuration to avoid using snc_redis services.

**Comment by prabhatkumarjena16** [comment]
> It happens to me the same issue installing the package in symfony 4.2. I'm looking how to resolve it. In the meantime, if anybody has started to analyse this issue thanks for sharing.

Have you installed any storage engine like Redis or doctrine cache?

**Comment by Pixadelic** [comment]
> > It happens to me the same issue installing the package in symfony 4.2. I'm looking how to resolve it. In the meantime, if anybody has started to analyse this issue thanks for sharing.
> 
> Have you installed any storage engine like Redis or doctrine cache?

Yes, at that time I was using redis as cache backend. Frankly I'm not able to go deeper as the concerned app is no longer up.

**Comment by vpArth** [comment]
So, snc/redis-bundle is required, not suggested for now?
I'm trying to use it with `storage_engine: memcache` and receive same error about redis..

**Comment by pohlaniacz** [comment]
> So, snc/redis-bundle is required, not suggested for now?
> I'm trying to use it with `storage_engine: memcache` and receive same error about redis..

as I remember my problem was because of dev environment (which for me didn't have redis but noxlogic didn't gave a sh.. even if was not enabled), so as workaroud I've made this (my config_dev.yml):
```
noxlogic_rate_limit:
    enabled: false
    storage_engine: simple_cache # this is "placebo" for bad configuration of RateLimitBundle
    simple_cache_service: simple_cache_for_ratelimit # this is "placebo" for bad configuration of RateLimitBundle

services:
    simple_cache_for_ratelimit:
        class: Symfony\Component\Cache\Simple\FilesystemCache
```

thing is, `enabled: false` was not enough, so have to fake the other 2 properties

**Comment by drzraf** [comment]
`bin/console -e test debug:config noxlogic_rate_limit`
```
noxlogic_rate_limit:
    storage_engine: simple_cache
    simple_cache_service: rate_limit_cache_storage
    rate_response_code: 429
    rate_response_message: 'You exceeded the rate limit'
    enabled: false
    redis_client: null
    redis_service: null
    php_redis_service: null
    memcache_client: default
    memcache_service: null
    doctrine_provider: null
    doctrine_service: null
    cache_service: null
    rate_response_exception: null
    display_headers: true
    headers:
        limit: X-RateLimit-Limit
        remaining: X-RateLimit-Remaining
        reset: X-RateLimit-Reset
    path_limits: {  }
    fos_oauth_key_listener: true
```

And still, `$ ./vendor/bin/simple-phpunit --debug -v`
```
1) App\Tests\Repository\RepositoryTest::testfindExisting
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "noxlogic_rate_limit.storage" has a dependency on a non-existent service "snc_redis.default_client".

app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:90
app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:40
app/vendor/symfony/dependency-injection/Compiler/Compiler.php:91
app/vendor/symfony/dependency-injection/ContainerBuilder.php:749
app/vendor/symfony/http-kernel/Kernel.php:596
app/vendor/symfony/http-kernel/Kernel.php:136
app/vendor/symfony/framework-bundle/Test/KernelTestCase.php:80
app/tests/Repository/RepositoryTest.php:55
```
